on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'

name: Lint

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Lint
      run: npm install && npm run lint
